import { getSkill, percentage, roleRequirements } from "@/lib/data";

const ids = (item, key = "skillIds") => Array.isArray(item?.[key]) ? item[key] : [];
export const consultationSkills = (consultation) => ids(consultation, "requiredSkillIds");
export const industryDemand = (data) => data.consultations.reduce((result, consultation) => {
  const openings = Number(consultation.openings) || 0;
  consultationSkills(consultation).forEach((skillId) => {
    if (!result[skillId]) result[skillId] = { skillId, openings: 0, employers: new Set(), consultations: 0 };
    result[skillId].openings += openings;
    result[skillId].employers.add(consultation.employerId);
    result[skillId].consultations += 1;
  });
  return result;
}, {});
export const demandRows = (data) => Object.values(industryDemand(data)).map((row) => ({ ...row, employers: row.employers.size, skill: getSkill(row.skillId), level: row.openings >= 20 ? "High" : row.openings >= 10 ? "Medium" : "Emerging" }));
export const requiredIndustrySkills = (data) => Object.keys(industryDemand(data));
export const totalOpenings = (data) => data.consultations.reduce((sum, item) => sum + (Number(item.openings) || 0), 0);
export const districtDemand = (data) => data.consultations.reduce((result, consultation) => { const district = consultation.district || "Unspecified"; result[district] = (result[district] || 0) + (Number(consultation.openings) || 0); return result; }, {});
export const courseAnalysis = (course, data) => { const required = requiredIndustrySkills(data); const covered = ids(course).filter((skillId) => required.includes(skillId)); return { covered, missing: required.filter((skillId) => !ids(course).includes(skillId)), alignment: percentage(covered.length, required.length) }; };
export const curriculumAnalysis = (curriculum, data) => { const required = requiredIndustrySkills(data); const covered = ids(curriculum).filter((skillId) => required.includes(skillId)); return { covered, missing: required.filter((skillId) => !ids(curriculum).includes(skillId)), alignment: percentage(covered.length, required.length) }; };
export const capacityRows = (data) => { const demand = industryDemand(data); const capacity = data.trainingCapacity.reduce((result, row) => { result[row.skillId] = (result[row.skillId] || 0) + (Number(row.availableSeats) || 0); return result; }, {}); return Object.values(demand).map((row) => ({ ...row, availableSeats: capacity[row.skillId] || 0, gap: row.openings - (capacity[row.skillId] || 0), skill: getSkill(row.skillId) })); };
export const trainerAnalysis = (trainer, data) => { const required = requiredIndustrySkills(data); const skills = ids(trainer); const matched = required.filter((skillId) => skills.includes(skillId)); return { matched, missing: required.filter((skillId) => !skills.includes(skillId)), readiness: percentage(matched.length, required.length) }; };
export const candidateAnalysis = (candidate, data) => { const required = requiredIndustrySkills(data).length ? requiredIndustrySkills(data) : roleRequirements; const skills = ids(candidate); const matched = required.filter((skillId) => skills.includes(skillId)); return { matched, missing: required.filter((skillId) => !skills.includes(skillId)), fit: percentage(matched.length, required.length) }; };
export const feedbackSummary = (data) => { const ratings = data.employerFeedback.map((item) => Number(item.rating)).filter(Boolean); return { count: ratings.length, average: ratings.length ? (ratings.reduce((sum, value) => sum + value, 0) / ratings.length).toFixed(1) : "0.0" }; };
export const coverageForSkill = (skillId, data) => {
  const courses = data.courses.filter((course) => ids(course).includes(skillId)).length;
  const trainers = data.trainers.filter((trainer) => ids(trainer).includes(skillId)).length;
  const candidates = data.candidates.filter((candidate) => ids(candidate).includes(skillId)).length;
  const curriculum = data.curriculums.some((item) => ids(item).includes(skillId));
  return { courses, trainers, candidates, curriculum };
};
export const skillIntelligenceRows = (data) => demandRows(data).map((row) => {
  const coverage = coverageForSkill(row.skillId, data);
  const coveredDimensions = [coverage.courses > 0, coverage.trainers > 0, coverage.candidates > 0, coverage.curriculum].filter(Boolean).length;
  const status = coveredDimensions === 4 ? "Adequately Covered" : row.level === "High" && coveredDimensions <= 1 ? "Critical Gap" : row.level === "High" ? "High Demand" : "Moderate Demand";
  return { ...row, coverage, status, explanation: status === "Critical Gap" ? `${row.skill.name} is highly demanded but has limited ecosystem coverage.` : status === "High Demand" ? `${row.skill.name} is requested by employers and needs broader ecosystem coverage.` : `${row.skill.name} has enough coverage for the current demand signal.` };
});
export const executiveMetrics = (data) => {
  const capacity = capacityRows(data);
  const alignments = data.courses.map((course) => courseAnalysis(course, data).alignment);
  const trainerScores = data.trainers.map((trainer) => trainerAnalysis(trainer, data).readiness);
  return { openings: totalOpenings(data), employers: new Set(data.consultations.map((item) => item.employerId)).size, highDemandSkills: demandRows(data).filter((row) => row.level === "High").length, districtsWithGaps: capacity.some((row) => row.gap > 0) ? new Set(data.consultations.map((item) => item.district || "Unspecified")).size : 0, availableSeats: capacity.reduce((sum, row) => sum + row.availableSeats, 0), capacityGap: capacity.reduce((sum, row) => sum + row.gap, 0), courseAlignment: alignments.length ? Math.round(alignments.reduce((sum, value) => sum + value, 0) / alignments.length) : 0, trainerReadiness: trainerScores.length ? Math.round(trainerScores.reduce((sum, value) => sum + value, 0) / trainerScores.length) : 0, candidates: data.candidates.length, placements: data.placements.length, feedback: feedbackSummary(data).count };
};
export const feedbackIntelligence = (data) => {
  const feedback = data.employerFeedback;
  const skillGaps = feedback.flatMap((item) => Array.isArray(item.skillGaps) ? item.skillGaps : []).reduce((result, skill) => { result[skill] = (result[skill] || 0) + 1; return result; }, {});
  const skillRatings = feedback.flatMap((item) => Object.entries(item.skillRatings || {})).reduce((result, [skill, rating]) => { if (!result[skill]) result[skill] = []; result[skill].push(Number(rating)); return result; }, {});
  const strongest = Object.entries(skillRatings).sort((a, b) => (b[1].reduce((x, y) => x + y, 0) / b[1].length) - (a[1].reduce((x, y) => x + y, 0) / a[1].length))[0];
  const weakest = Object.entries(skillRatings).sort((a, b) => (a[1].reduce((x, y) => x + y, 0) / a[1].length) - (b[1].reduce((x, y) => x + y, 0) / b[1].length))[0];
  return { count: feedback.length, completionRate: data.placements.length ? Math.round(feedback.length / data.placements.length * 100) : 0, mostReportedGap: Object.entries(skillGaps).sort((a, b) => b[1] - a[1])[0]?.[0] || "No repeated gap yet", strongestSkill: strongest ? getSkill(strongest[0]).name : "Not enough feedback", weakestSkill: weakest ? getSkill(weakest[0]).name : "Not enough feedback" };
};
export const skillPulseDetail = (skillId, data) => {
  const demand = demandRows(data).find((row) => row.skillId === skillId) || { skillId, openings: 0, employers: 0, level: "Emerging", skill: getSkill(skillId) };
  const coverage = coverageForSkill(skillId, data);
  const capacity = capacityRows(data).find((row) => row.skillId === skillId) || { availableSeats: 0, gap: 0 };
  const placements = data.placements.filter((placement) => data.candidates.find((candidate) => candidate.id === placement.candidateId)?.skillIds.includes(skillId)).length;
  const relevantCourses = data.courses.filter((course) => ids(course).includes(skillId)); const courseAlignment = relevantCourses.length ? Math.round(relevantCourses.map((course) => courseAnalysis(course, data).alignment).reduce((sum, value) => sum + value, 0) / relevantCourses.length) : 0;
  return { ...demand, coverage, availableSeats: capacity.availableSeats, capacityGap: capacity.gap, placements, courseAlignment, status: skillIntelligenceRows(data).find((row) => row.skillId === skillId)?.status || "No current demand" };
};
export const districtPriorityRows = (data) => {
  const districts = new Set([...data.consultations.map((item) => item.district), ...data.trainingCapacity.map((item) => item.district), ...data.candidates.map((item) => item.district)].filter(Boolean));
  return [...districts].map((district) => {
    const consultations = data.consultations.filter((item) => item.district === district); const openings = consultations.reduce((sum, item) => sum + (Number(item.openings) || 0), 0); const seats = data.trainingCapacity.filter((item) => item.district === district).reduce((sum, item) => sum + (Number(item.availableSeats) || 0), 0); const criticalSkills = capacityRows(data).filter((row) => row.gap > 0 && data.trainingCapacity.some((item) => item.district === district && item.skillId === row.skillId)).map((row) => row.skill.name); const candidates = data.candidates.filter((item) => item.district === district).length; const placements = data.placements.filter((item) => item.district === district).length; const gap = openings - seats; const priority = gap > 0 && criticalSkills.length >= 2 ? "Critical Intervention" : gap > 0 ? "High Priority" : openings ? "Monitor" : "Balanced"; return { district, openings, seats, gap, criticalSkills, institutes: new Set(data.trainingCapacity.filter((item) => item.district === district).map((item) => item.instituteId).filter(Boolean)).size, candidates, placements, priority };
  }).sort((a, b) => b.gap - a.gap);
};
export const simulateIntervention = (data, { skillId, additionalSeats, additionalTrainers, curriculumSkill }) => {
  const current = skillPulseDetail(skillId, data); const addedSeats = Number(additionalSeats) || 0; const addedTrainers = Number(additionalTrainers) || 0; const currentCurriculum = current.coverage.curriculum; const simulatedCurriculum = currentCurriculum || curriculumSkill === skillId; const currentTrainerCoverage = current.coverage.trainers; const simulatedTrainerCoverage = currentTrainerCoverage + addedTrainers; const currentCourseAlignment = data.courses.length ? Math.round(data.courses.map((course) => courseAnalysis(course, data).alignment).reduce((sum, value) => sum + value, 0) / data.courses.length) : 0; const simulatedCourseAlignment = curriculumSkill === skillId ? Math.min(100, currentCourseAlignment + Math.round(100 / Math.max(requiredIndustrySkills(data).length, 1))) : currentCourseAlignment; const missingCandidates = data.candidates.filter((candidate) => !candidate.skillIds.includes(skillId)).length; const coveredCandidates = Math.min(missingCandidates, Math.floor(addedSeats)); return { current, projected: { availableSeats: current.availableSeats + addedSeats, gap: current.capacityGap - addedSeats, trainerCoverage: simulatedTrainerCoverage, curriculum: simulatedCurriculum, courseAlignment: simulatedCourseAlignment, candidatesCovered: coveredCandidates, candidateGapReduction: missingCandidates ? Math.round(coveredCandidates / missingCandidates * 100) : 0 }, explanation: addedSeats ? `Adding ${addedSeats} seats would theoretically reduce the ${current.skill.name} capacity gap by ${Math.min(addedSeats, Math.max(current.capacityGap, 0))} seats in this prototype scenario.` : curriculumSkill === skillId ? `Adding ${current.skill.name} to curriculum coverage would project course alignment from ${currentCourseAlignment}% to ${simulatedCourseAlignment}%.` : addedTrainers ? `Adding ${addedTrainers} trainer(s) would increase projected ${current.skill.name} trainer coverage from ${currentTrainerCoverage} to ${simulatedTrainerCoverage}.` : `Change the controls to explore a projected intervention for ${current.skill.name}.` };
};
export const actionPriority = (score) => score >= 80 ? "Critical" : score >= 60 ? "High" : score >= 35 ? "Medium" : "Monitor";
export const priorityActions = (data) => {
  const actions = []; const rows = skillIntelligenceRows(data); const capacity = capacityRows(data);
  capacity.filter((row) => row.gap > 0).sort((a, b) => b.gap - a.gap).slice(0, 3).forEach((row) => { const score = Math.min(100, Math.round(row.gap / Math.max(row.openings, 1) * 100) + (row.level === "High" ? 35 : 15)); actions.push({ id: `capacity-${row.skillId}`, type: "Capacity", priority: actionPriority(score), score, location: data.trainingCapacity.find((item) => item.skillId === row.skillId)?.district || "District-wide", issue: `${row.skill.name} demand exceeds available training seats.`, evidence: `${row.openings} openings · ${row.availableSeats} seats · ${row.gap} seat gap`, action: `Increase ${row.skill.name} training capacity by approximately ${row.gap} seats.`, affected: "capacity", skillId: row.skillId }); });
  rows.filter((row) => !row.coverage.curriculum).sort((a, b) => b.openings - a.openings).slice(0, 2).forEach((row) => actions.push({ id: `curriculum-${row.skillId}`, type: "Curriculum", priority: actionPriority(row.openings + 20), score: Math.min(100, row.openings + 20), location: "District-wide", issue: `${row.skill.name} is demanded by employers but missing from curriculum coverage.`, evidence: `${row.openings} openings · ${row.employers} employer(s) · curriculum missing`, action: `Add ${row.skill.name} to the selected curriculum.`, affected: "curriculum", skillId: row.skillId }));
  rows.filter((row) => row.level === "High" && row.coverage.trainers <= 1).sort((a, b) => b.openings - a.openings).slice(0, 2).forEach((row) => actions.push({ id: `trainer-${row.skillId}`, type: "Trainer", priority: actionPriority(row.openings + 10), score: Math.min(100, row.openings + 10), location: "District-wide", issue: `${row.skill.name} demand is high while trainer coverage is low.`, evidence: `${row.openings} openings · ${row.coverage.trainers} trainer(s) · high demand`, action: `Prioritize ${row.skill.name} trainer upskilling.`, affected: "trainers", skillId: row.skillId }));
  rows.filter((row) => row.level === "High" && row.coverage.candidates < Math.max(2, row.employers * 2)).slice(0, 2).forEach((row) => actions.push({ id: `candidate-${row.skillId}`, type: "Candidate", priority: actionPriority(row.openings), score: Math.min(100, row.openings), location: "District-wide", issue: `Candidates have limited ${row.skill.name} coverage against current demand.`, evidence: `${row.openings} openings · ${row.coverage.candidates} candidate(s) with skill`, action: `Add targeted ${row.skill.name} learning to candidate pathways.`, affected: "candidates", skillId: row.skillId }));
  return actions.sort((a, b) => b.score - a.score);
};
export const pipelineMetrics = (data, district = "All", role = "All") => {
  const consultations = data.consultations.filter((item) => (district === "All" || item.district === district) && (role === "All" || item.role === role)); const openings = consultations.reduce((sum, item) => sum + (Number(item.openings) || 0), 0); const seats = data.trainingCapacity.filter((item) => district === "All" || item.district === district).reduce((sum, item) => sum + (Number(item.availableSeats) || 0), 0); const candidates = data.candidates.filter((candidate) => district === "All" || candidate.district === district); const placements = data.placements.filter((placement) => district === "All" || placement.district === district); const placementIds = new Set(placements.map((placement) => placement.id)); const feedback = data.employerFeedback.filter((item) => placementIds.has(item.placementId)); const readyCandidates = candidates.filter((candidate) => candidateAnalysis(candidate, data).fit >= 80).length; return { openings, seats, candidates: candidates.length, readyCandidates, placements: placements.length, feedback: feedback.length, district, role };
};
export const pipelineConversions = (pipeline) => ({ trainingCoverage: pipeline.openings ? Math.round(pipeline.seats / pipeline.openings * 100) : null, candidateReadiness: pipeline.candidates ? Math.round(pipeline.readyCandidates / pipeline.candidates * 100) : null, placementConversion: pipeline.candidates ? Math.round(pipeline.placements / pipeline.candidates * 100) : null, feedbackCoverage: pipeline.placements ? Math.round(pipeline.feedback / pipeline.placements * 100) : null });
export const hierarchyOptions = (data) => ({ districts: ["All", ...new Set(data.consultations.map((item) => item.district).filter(Boolean))], roles: ["All", ...new Set(data.consultations.map((item) => item.role).filter(Boolean))] });
export const prototypeImpactScore = (current, projected) => {
  const capacity = current.capacityGap > 0 ? Math.max(0, Math.min(100, (current.capacityGap - Math.max(projected.gap, 0)) / current.capacityGap * 100)) : 0; const trainer = current.coverage.trainers ? Math.max(0, Math.min(100, (projected.trainerCoverage - current.coverage.trainers) / current.coverage.trainers * 100)) : projected.trainerCoverage ? 100 : 0; const course = Math.max(0, projected.courseAlignment - (current.courseAlignment || 0)); const candidate = projected.candidateGapReduction || 0; const curriculum = projected.curriculum && !current.coverage.curriculum ? 100 : 0; const breakdown = { capacity: Math.round(capacity), trainer: Math.round(trainer), course: Math.round(Math.min(course * 5, 100)), candidate: Math.round(candidate), curriculum }; const score = Math.round(breakdown.capacity * .35 + breakdown.trainer * .2 + breakdown.course * .2 + breakdown.candidate * .15 + breakdown.curriculum * .1); return { score, breakdown };
};