"use client";

import { useMemo, useState } from "react";
import { candidateAnalysis, capacityRows, courseAnalysis, curriculumAnalysis, demandRows, feedbackSummary, skillIntelligenceRows, trainerAnalysis } from "@/lib/analytics";
import { getSkill, roleRequirements } from "@/lib/data";

const steps = [
  ["Industry demand", "Industry demand enters the ecosystem through employer requirements."],
  ["Labour market intelligence", "The platform aggregates employer demand into actionable market intelligence."],
  ["Skill intelligence", "The system identifies the skills driving current demand."],
  ["Skill gap", "We move from demand to identifying the actual skills shortage."],
  ["Course intelligence", "The platform compares industry requirements with available training."],
  ["Curriculum alignment", "The same intelligence identifies what needs to change in the curriculum."],
  ["Training capacity", "The government can see where training supply is below industry demand."],
  ["Trainer intelligence", "The system also identifies trainer readiness gaps."],
  ["Candidate role fit", "The same industry signal becomes an actionable path for candidates."],
  ["Placement", "Training outcomes are captured as actual placement outcomes."],
  ["Employer feedback", "Employer feedback gives us outcome-level information."],
  ["Closed loop", "Industry demand drives skilling decisions, and placement feedback improves future planning."],
];

function Badge({ children, tone = "blue" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
function Card({ children, className = "" }) { return <section className={`card guided-card ${className}`}>{children}</section>; }
function Metric({ label, value, detail }) { return <div className="guided-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function SkillList({ ids = [] }) { return <div className="guided-tags">{ids.map((id) => <Badge key={id}>{getSkill(id).name}</Badge>)}</div>; }
function Progress({ value, tone = "blue" }) { return <div className="progress"><span className={`progress-fill fill-${tone}`} style={{ width: `${Math.max(0, Math.min(value || 0, 100))}%` }} /></div>; }

function StepContent({ step, data }) {
  const demand = demandRows(data);
  const required = demand.map((row) => row.skillId);
  const powerBi = demand.find((row) => row.skillId === "power-bi") || { openings: 0, employers: 0 };
  const course = data.courses[0];
  const curriculum = data.curriculums[0];
  const trainer = data.trainers[0];
  const candidate = data.candidates[0];
  const courseResult = course ? courseAnalysis(course, data) : { covered: [], missing: [], alignment: 0 };
  const curriculumResult = curriculum ? curriculumAnalysis(curriculum, data) : { covered: [], missing: [], alignment: 0 };
  const trainerResult = trainer ? trainerAnalysis(trainer, data) : { matched: [], missing: [], readiness: 0 };
  const candidateResult = candidate ? candidateAnalysis(candidate, data) : { matched: [], missing: [], fit: 0 };
  const capacity = capacityRows(data);
  const capacityTotal = capacity.reduce((sum, row) => sum + row.availableSeats, 0);
  const capacityGap = capacity.reduce((sum, row) => sum + row.gap, 0);
  const feedback = feedbackSummary(data);
  if (step === 0) return <Card className="guided-hero-card"><div className="guided-role-line"><div><div className="eyebrow">EMPLOYER DEMAND</div><h2>TechNova Solutions</h2><p>Pune · Technology Services</p></div><Badge tone="coral">{data.employers[0]?.status || "Hiring"}</Badge></div><div className="guided-metric-grid"><Metric label="Role" value={data.employers[0]?.role || "Data Operations Analyst"} detail="target role" /><Metric label="Openings" value={data.employers[0]?.openings || 0} detail="industry demand" /><Metric label="Required skills" value={required.length} detail="canonical Skill IDs" /></div><SkillList ids={data.employers[0]?.requiredSkillIds || roleRequirements} /></Card>;
  if (step === 1) return <Card><div className="guided-metric-grid"><Metric label="Openings" value={data.consultations.reduce((sum, item) => sum + Number(item.openings || 0), 0)} detail="aggregated consultations" /><Metric label="Employers" value={new Set(data.consultations.map((item) => item.employerId)).size} detail="requesting talent" /><Metric label="District" value={data.consultations[0]?.district || "Unavailable"} detail="active demand location" /><Metric label="Roles" value={new Set(data.consultations.map((item) => item.role)).size} detail="role signals" /></div><div className="guided-callout"><b>Live market signal</b><p>{demand.length} canonical skills are being requested across connected employer consultations.</p></div></Card>;
  if (step === 2) return <Card><div className="guided-focus"><div className="guided-focus-icon">✦</div><div><div className="eyebrow">HIGHLIGHTED SKILL</div><h2>Power BI</h2><p>{powerBi.openings} openings from {powerBi.employers} employer(s). Status: <Badge tone="yellow">{skillIntelligenceRows(data).find((row) => row.skillId === "power-bi")?.status || "No current demand"}</Badge></p></div></div><div className="guided-metric-grid"><Metric label="Demand" value={powerBi.openings} detail="openings" /><Metric label="Courses" value={data.courses.filter((item) => item.skillIds.includes("power-bi")).length} detail="course coverage" /><Metric label="Trainers" value={data.trainers.filter((item) => item.skillIds.includes("power-bi")).length} detail="trainer coverage" /><Metric label="Candidates" value={data.candidates.filter((item) => item.skillIds.includes("power-bi")).length} detail="candidate coverage" /></div></Card>;
  if (step === 3) return <Card><h2>Data Operations Analyst skill gap</h2><p className="guided-muted">Required skills compared with current coverage.</p><div className="guided-skill-rows">{required.map((id) => { const covered = data.courses.some((item) => item.skillIds.includes(id)) && data.trainers.some((item) => item.skillIds.includes(id)); return <div key={id}><b>{getSkill(id).name}</b><span>{covered ? <Badge tone="green">Covered</Badge> : <Badge tone="coral">Gap</Badge>}</span></div>; })}</div><div className="guided-callout warning"><b>Why this matters</b><p>Power BI has a current capacity gap of {Math.max(powerBi.openings - (capacity.find((row) => row.skillId === "power-bi")?.availableSeats || 0), 0)} seats.</p></div></Card>;
  if (step === 4) return <Card><div className="guided-course-title"><div className="course-icon">▤</div><div><h2>{course?.name || "No course available"}</h2><p>{course?.duration || "Unavailable"} · {course?.mode || ""}</p></div><Badge tone="green">{courseResult.alignment}% aligned</Badge></div><Progress value={courseResult.alignment} tone="green" /><div className="guided-two-col"><div><span>Matched skills</span><SkillList ids={courseResult.covered} /></div><div><span>Missing skills</span><SkillList ids={courseResult.missing} /></div></div><p className="guided-explanation">This course matches {courseResult.covered.length} of {required.length} currently demanded skills.</p></Card>;
  if (step === 5) return <Card><h2>{curriculum?.name || "Curriculum unavailable"}</h2><p>{curriculum?.owner || "No curriculum owner recorded"}</p><div className="guided-alignment"><strong>{curriculumResult.alignment}%</strong><div><span>Curriculum alignment</span><Progress value={curriculumResult.alignment} tone="yellow" /></div></div><div className="guided-callout warning"><b>Recommended change</b><p>{curriculumResult.missing.length ? `Add ${curriculumResult.missing.map((id) => getSkill(id).name).join(", ")} to improve alignment.` : "No missing demanded skills detected."}</p></div></Card>;
  if (step === 6) return <Card><div className="guided-metric-grid"><Metric label="Industry demand" value={data.consultations.reduce((sum, item) => sum + Number(item.openings || 0), 0)} detail="openings" /><Metric label="Available seats" value={capacityTotal} detail="relevant capacity" /><Metric label="Capacity gap" value={capacityGap} detail="demand minus seats" /><Metric label="Priority district" value={data.consultations[0]?.district || "Unavailable"} detail="current signal" /></div><div className="guided-callout warning"><b>Government decision</b><p>Training supply is below the current industry demand signal. Expand seats for the largest skill-level gaps.</p></div></Card>;
  if (step === 7) return <Card><div className="guided-focus"><div className="avatar large">R</div><div><h2>{trainer?.name || "Trainer unavailable"}</h2><p>{trainer?.experience || ""} experience · Pune Digital Academy</p></div><Badge tone="yellow">{trainerResult.readiness}% ready</Badge></div><div className="guided-two-col"><div><span>Current skills</span><SkillList ids={trainerResult.matched} /></div><div><span>Upskilling needed</span><SkillList ids={trainerResult.missing} /></div></div><p className="guided-explanation">High-demand skills missing from this profile become explainable upskilling recommendations.</p></Card>;
  if (step === 8) return <Card><div className="guided-role-line"><div><div className="eyebrow">TARGET ROLE</div><h2>Data Operations Analyst</h2><p>TechNova Solutions · Pune</p></div><div className="guided-score">{candidateResult.fit}%<small>role fit</small></div></div><div className="guided-two-col"><div><span>Matched skills</span><SkillList ids={candidateResult.matched} /></div><div><span>Missing skills</span><SkillList ids={candidateResult.missing} /></div></div><div className="guided-callout"><b>Recommended pathway</b><p>{course?.name || "Relevant course"} covers {courseResult.covered.filter((id) => candidateResult.missing.includes(id)).length} of the candidate&apos;s missing skills.</p></div></Card>;
  if (step === 9) return <Card><div className="guided-metric-grid"><Metric label="Candidate" value={data.candidates.find((item) => item.status === "Placed")?.name || "Recorded candidate"} detail="placement record" /><Metric label="Employer" value={data.employers[0]?.name || "Unavailable"} detail="employer" /><Metric label="Role" value={data.placements[0]?.role || "Unavailable"} detail="placed role" /><Metric label="Status" value={data.placements[0]?.status || "Unavailable"} detail={data.placements[0]?.placedAt || "date unavailable"} /></div><div className="guided-callout"><b>Outcome captured</b><p>The placement is connected to candidate, employer, role, district, and date.</p></div></Card>;
  if (step === 10) return <Card><div className="guided-focus"><div className="guided-focus-icon">↗</div><div><div className="eyebrow">EMPLOYER FEEDBACK</div><h2>{feedback.count} feedback record(s)</h2><p>Average employer rating: <b>{feedback.average} / 5</b></p></div></div><div className="guided-callout"><b>Outcome-level learning</b><p>{data.employerFeedback[0]?.note || "No feedback comment recorded."}</p></div><p className="guided-explanation">Feedback is connected to placement outcomes and informs future skill and training decisions.</p></Card>;
  return <Card className="guided-loop-card"><div className="guided-loop"><span>Industry Demand</span><i>↓</i><span>Skill Intelligence</span><i>↓</i><span>Skill Gap</span><i>↓</i><span>Training & Curriculum</span><i>↓</i><span>Trainer Readiness</span><i>↓</i><span>Candidate Preparation</span><i>↓</i><span>Placement</span><i>↓</i><span>Employer Feedback</span><i>↺</i><strong>Updated Intelligence</strong></div><p>Industry demand drives skilling decisions, and placement feedback improves future planning.</p></Card>;
}

export default function GuidedDemo({ data, onExit }) {
  const [step, setStep] = useState(() => typeof window === "undefined" ? 0 : Number(window.localStorage.getItem("skillconnect-guided-step") || 0)); const active = steps[step];
  const goToStep = (nextStep) => { setStep(nextStep); window.localStorage.setItem("skillconnect-guided-step", String(nextStep)); };
  return <main className="guided-page"><header className="guided-header"><div className="guided-brand"><div className="brand-mark">SC</div><div><b>SkillConnect</b><small>Guided SIH Demo</small></div></div><div className="guided-header-actions"><span>Step {step + 1} of {steps.length}</span><button onClick={onExit}>Exit Demo</button></div></header><div className="guided-progress"><span style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div><main className="guided-content"><div className="guided-intro"><div><div className="eyebrow">SIH 2026 · Pune district pilot</div><h1>{active[0]}</h1><p>{active[1]}</p></div><div className="guided-step-index">{String(step + 1).padStart(2, "0")}</div></div><div className="guided-stage"><StepContent step={step} data={data} /></div><footer className="guided-footer"><button className="guided-back" onClick={() => goToStep(Math.max(step - 1, 0))} disabled={step === 0}>← Back</button><div className="guided-dots">{steps.map((item, index) => <button key={item[0]} aria-label={`Go to step ${index + 1}`} className={index === step ? "active" : ""} onClick={() => goToStep(index)} />)}</div><button className="button button-primary" onClick={() => step === steps.length - 1 ? onExit() : goToStep(Math.min(step + 1, steps.length - 1))}>{step === steps.length - 1 ? "Return to workspace" : "Next step →"}</button></footer></main></main>;
}
